---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment-replicas
spec:
  replicas: {{ .Values.deployment.numReplicas }}
  selector:
    matchLabels:
      app: sample-go-web-app
  template:
    metadata:
      labels:
        app: sample-go-web-app
    spec:
      containers:
        - name: webserver-simple
          image: {{ .Values.deployment.dockerImage }} 
          ports:
            - containerPort: {{ .Values.deployment.containerPort }}
