apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  type: {{ Values.serviceType }}
  selector:
    app: sample-go-web-app
  ports:
    - nodePort: {{ Values.service.nodePort }} 
      protocol: {{ Values.service.protocolType }} 
      port: {{Values.service.port }} 
